steps:
  # 1. Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', '$_IMAGE_PATH', 
      '-f', 'Dockerfile', 
      '.'
    ]

  # 2. Login to AWS ECR and Push
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install AWS CLI
        apt-get update && apt-get install -y awscli
        
        export AWS_ACCESS_KEY_ID=$$AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY=$$AWS_SECRET_ACCESS_KEY
        export AWS_DEFAULT_REGION="eu-west-1"
        
        # Ensure the ECR repository exists
        aws ecr describe-repositories --repository-names "$_AWS_REPO_NAME" --region $$AWS_DEFAULT_REGION || \
          aws ecr create-repository --repository-name "$_AWS_REPO_NAME" --region $$AWS_DEFAULT_REGION
        
        # Login to AWS ECR
        aws ecr get-login-password --region $$AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $_AWS_ACCOUNT_ID.dkr.ecr.$$AWS_DEFAULT_REGION.amazonaws.com
        
        # Tag for AWS
        docker tag $_IMAGE_PATH $_AWS_ACCOUNT_ID.dkr.ecr.$$AWS_DEFAULT_REGION.amazonaws.com/$_AWS_REPO_NAME:latest
        
        # Push to AWS
        docker push $_AWS_ACCOUNT_ID.dkr.ecr.$$AWS_DEFAULT_REGION.amazonaws.com/$_AWS_REPO_NAME:latest
    secretEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']

# This section pulls the secrets from Secret Manager and maps them to environment variables
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/AWS_ACCESS_KEY_ID/versions/latest
    env: 'AWS_ACCESS_KEY_ID'
  - versionName: projects/$PROJECT_ID/secrets/AWS_SECRET_ACCESS_KEY/versions/latest
    env: 'AWS_SECRET_ACCESS_KEY'

images:
  - '$_IMAGE_PATH'
